basePath: /
definitions:
  schema.HTTPError:
    properties:
      error:
        $ref: '#/definitions/schema.HTTPErrorItem'
        description: 错误项
        type: object
    type: object
  schema.HTTPErrorItem:
    properties:
      code:
        description: 错误码
        type: integer
      message:
        description: 错误信息
        type: string
    type: object
  schema.LoginParam:
    properties:
      captcha_code:
        description: 验证码
        type: string
      captcha_id:
        description: 验证码ID
        type: string
      password:
        description: 密码(md5加密)
        type: string
      user_name:
        description: 用户名
        type: string
    required:
    - captcha_code
    - captcha_id
    - password
    - user_name
    type: object
  schema.LoginTokenInfo:
    properties:
      access_token:
        description: 访问令牌
        type: string
      expires_at:
        description: 令牌到期时间戳
        type: integer
      token_type:
        description: 令牌类型
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: cappuccino
  version: latest
paths:
  /api/v1/login:
    post:
      parameters:
      - description: 请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.LoginParam'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.LoginTokenInfo'
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 用户登录
      tags:
      - 登录管理
  /api/v1/login/captcha:
    get:
      parameters:
      - description: 验证码ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: 图形验证码
        "400":
          description: '{error:{code:0,message:无效的请求参数}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
        "500":
          description: '{error:{code:0,message:服务器错误}}'
          schema:
            $ref: '#/definitions/schema.HTTPError'
      summary: 响应图形验证码
      tags:
      - 登录管理
  /api/v1/login/captchaId:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取验证码信息
      tags:
      - 登录管理
  /cappuccino/api/v1:
    get:
      description: 获取平台版本
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取平台版本
      tags:
      - 获取平台版本
swagger: "2.0"
