basePath: /
definitions:
  dto.CreateUserRequest:
    properties:
      loginName:
        type: string
      nickName:
        type: string
    required:
    - loginName
    - nickName
    type: object
  dto.GetAccessTokenRequest:
    properties:
      login_name:
        type: string
      password:
        type: string
    required:
    - login_name
    - password
    type: object
  dto.GetAccessTokenResponse:
    properties:
      accessToken:
        type: string
    required:
    - accessToken
    type: object
  dto.UpdateUserRequest:
    properties:
      id:
        type: string
      nickName:
        type: string
      phone:
        type: string
    required:
    - nickName
    - phone
    type: object
info:
  contact: {}
  license: {}
  title: cappuccino
  version: latest
paths:
  /cappuccino/api/admin:
    get:
      description: 获取后台版本
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: 获取后台版本
      tags:
      - 后台
  /cappuccino/api/admin/challenge:
    get:
      consumes:
      - application/json
      description: Token检查
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "401":
          description: Unauthorized
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: Token检查
      tags:
      - 后台
  /cappuccino/api/admin/getAccessToken:
    post:
      consumes:
      - application/json
      description: 获取Token
      parameters:
      - description: 获取Token信息
        in: body
        name: GetAccessTokenRequest
        required: true
        schema:
          $ref: '#/definitions/dto.GetAccessTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAccessTokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GetAccessTokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.GetAccessTokenResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GetAccessTokenResponse'
      summary: 获取Token
      tags:
      - 后台
  /cappuccino/api/admin/user:
    post:
      consumes:
      - application/json
      description: 创建用户
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 创建用户
      tags:
      - 后台
    put:
      consumes:
      - application/json
      description: 更新用户
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: UpdateUserRequest
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
        "400":
          description: Bad Request
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      summary: 更新用户
      tags:
      - 后台
swagger: "2.0"
